/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.WorkAreas.AdminRole;

import online.Business;
import UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp.ManageUserAccountsJPanel;
import UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp.ManagePersonsJPanel;
import javax.swing.JOptionPane;

import javax.swing.JPanel;

/**
 *
 * @author kal
 */
public class AdminRoleWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;

    /**
     * Creates new form UnitRiskWorkArea
     */
    public AdminRoleWorkAreaJPanel(Business b, JPanel clp) {

        business = b;
        this.CardSequencePanel = clp;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUsers = new javax.swing.JButton();
        btnSems = new javax.swing.JButton();
        txtSem = new javax.swing.JTextField();
        lblSem = new javax.swing.JLabel();

        setForeground(new java.awt.Color(51, 51, 51));

        btnUsers.setBackground(new java.awt.Color(102, 153, 255));
        btnUsers.setFont(getFont());
        btnUsers.setForeground(new java.awt.Color(255, 255, 255));
        btnUsers.setText("View User Accounts");
        btnUsers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUsers.setMaximumSize(new java.awt.Dimension(200, 40));
        btnUsers.setMinimumSize(new java.awt.Dimension(20, 23));
        btnUsers.setPreferredSize(new java.awt.Dimension(240, 30));
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnSems.setBackground(new java.awt.Color(102, 153, 255));
        btnSems.setFont(getFont());
        btnSems.setForeground(new java.awt.Color(255, 255, 255));
        btnSems.setText("Release Semester");
        btnSems.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSems.setMaximumSize(new java.awt.Dimension(200, 40));
        btnSems.setMinimumSize(new java.awt.Dimension(20, 20));
        btnSems.setPreferredSize(new java.awt.Dimension(240, 25));
        btnSems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSemsActionPerformed(evt);
            }
        });

        lblSem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSem.setText("Semester");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(lblSem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(txtSem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(406, 406, 406)
                        .addComponent(btnSems, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(509, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSems, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsersIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:

        ManageUserAccountsJPanel aos = new ManageUserAccountsJPanel(business, CardSequencePanel);

        CardSequencePanel.add("ManageVulns", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnUsersIdentifyResourceAssetsActionPerformed

    private void btnSemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSemsActionPerformed
        if (txtSem.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Please enter semester!");
            return;
        }
        for (String sem : business.getSems()) {
            if (sem.equals(txtSem.getText())) {
                JOptionPane.showMessageDialog(this, "Semester already exists!");
                return;
            }
        }
        business.newCourseSchedule(txtSem.getText());
        JOptionPane.showMessageDialog(this, "Semester added successfully!");
    }//GEN-LAST:event_btnSemsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSems;
    private javax.swing.JButton btnUsers;
    private javax.swing.JLabel lblSem;
    private javax.swing.JTextField txtSem;
    // End of variables declaration//GEN-END:variables

}
